version: '3.3'
services: 
  nginx:
     build: ./nginx/
     ports:
       - 3001:80
     volumes:
         - ./backend/:/var/www/html/
  php:
     build: ./backend/
     expose:
       - 9000
     volumes:
        - ./backend/:/var/www/html/
  frontend-react:
    hostname: frontend-react
    container_name: frontend-react
    build: ./frontend
    ports:
      - 3000:3000
